server:
  port: 8084

# DataSource Config
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/file-dispatch
    username: root
    password: 123456
  redis:
    host: 127.0.0.1
    port: 6379

